version: '3.8'

services:

  postgres:
    container_name: postgres_students
    image: postgres:15.2
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  nats:
    image: 'nats:2.10.5'
    ports:
      - "4222:4222"
      - "8222:8222"

  gateway:
    container_name: gateway
    build:
      context: ./server
      dockerfile: ./apps/gateway/Dockerfile
    env_file:
      - .env
    depends_on:
      - nats
      - postgres
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "8080:8080"

  students:
    container_name: students
    build:
      context: ./server
      dockerfile: ./apps/students/Dockerfile
    env_file:
      - .env
    depends_on:
      - nats
      - postgres
    volumes:
      - ./server:/app
      - /app/node_modules